# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_user',
        ),
    ]
