# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20180412_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(default='static/public/img/9110.jpg', upload_to='static/public/img'),
        ),
    ]
