# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20180412_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Types',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='num',
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(upload_to='static/public/img'),
        ),
    ]
