# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20180413_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
