# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20180420_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='nums',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
