# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='nums',
            field=models.IntegerField(default=1),
        ),
    ]
