# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_auto_20180423_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods'),
        ),
    ]
